services:
  - type: web
    name: cudliy-backend
    env: node
    plan: starter
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: GOOGLE_CLOUD_PROJECT_ID
        sync: false
      - key: GOOGLE_CLOUD_BUCKET_NAME
        sync: false
      - key: GOOGLE_CLOUD_PRIVATE_KEY
        sync: false
      - key: GOOGLE_CLOUD_CLIENT_EMAIL
        sync: false
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health
    autoDeploy: true
